parameters:
  - name: package_name
    default: 'antlr4-cpp-runtime'

steps:
  - checkout: self
  - script: |
      choco install -y zip ninja
    displayName: 'Install Prerequisites'
  - powershell: |
      $ErrorActionPreference = 'Stop'
      cd runtime/Cpp
      mkdir build
      cd build
      cmake ../ -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DANTLR4_INSTALL:bool=true -DCMAKE_INSTALL_PREFIX:path=../${{ parameters.package_name }}
      ninja install
    displayName: 'Build'
  - powershell: |
      cd runtime/Cpp
      zip -r ${{ parameters.package_name }}-windows.zip ${{ parameters.package_name }}
      mkdir $(System.DefaultWorkingDirectory)/archives
      mv ${{ parameters.package_name }}-windows.zip $(System.DefaultWorkingDirectory)/archives
    displayName: 'Create Assets'
